databases:
  - name: todo
    databaseName: mydatabase
    user: user99

services:
  - type: web
    name: todo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4